apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: rce-app
spec:
  containers:
  - name: rce-app
    image: icecream0x01/rce-app:latest
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
    - name: container-2
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
    - name: container-3
      image: nginx

