apiVersion: v1
kind: Service
metadata:
  name: rce-app-service
spec:
  selector:
    app: rce-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: spring4shell-service
spec:
  selector:
    app: spring4shell
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
